# 使用Python基础镜像
FROM python:3.10-slim

# 设置工作目录
WORKDIR /app

# 复制当前目录的所有文件到容器内的/app目录
COPY . .

# 安装所需的Python依赖包
RUN pip install --no-cache-dir pandas backtrader oss2 alibabacloud_credentials

# 启动命令
CMD ["python", "hpc_demo.py"]
